{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "51edb8a6",
   "metadata": {},
   "outputs": [],
   "source": [
    "\"\"\"Module core/configs provide project base settings\"\"\"\n",
    "import glob\n",
    "import json\n",
    "import os\n",
    "import os.path\n",
    "\n",
    "\n",
    "class Settings:\n",
    "    PROJECT_NAME: str = 'Kraken'\n",
    "    DEVICE = 'neo'\n",
    "    CONFIG_INFO = {\n",
    "        'host': '127.0.0.1',\n",
    "        'port': 8712,\n",
    "        'controlmode': 'socket',\n",
    "        'channel_count': 9,\n",
    "        'sample_rate': 1000,\n",
    "        'buffer_length': 1,\n",
    "        'channel_labels': [\n",
    "            'CH001',\n",
    "            'CH002',\n",
    "            'CH003',\n",
    "            'CH004',\n",
    "            'CH005',\n",
    "            'CH006',\n",
    "            'CH007',\n",
    "            'CH008',\n",
    "            'STIM'\n",
    "        ],\n",
    "        'strips': [['CH001', 'CH002', 'CH003', 'CH004'], \n",
    "                   ['CH005', 'CH006', 'CH007', 'CH008']],\n",
    "        'reref': 'average', \n",
    "        'normP': [[-14, -13.4], \n",
    "             [-13.98, -13.37], \n",
    "             [-13.82, -13.2], \n",
    "             [-13.8, -13], \n",
    "             [-14, -13.46], \n",
    "             [-14.09, -13.4], \n",
    "             [-14.02, -13.34]],\n",
    "        'visbands': [60, 90],\n",
    "        'stds': 3,\n",
    "        'nperseg': 1000\n",
    "    }\n",
    "    \n",
    "    FINGERMODEL_IDS = {\n",
    "        'rest': 0,\n",
    "        'cylinder': 1,\n",
    "        'ball': 2,\n",
    "        'flex': 3,\n",
    "        'double': 4,\n",
    "        'treble': 5,\n",
    "        'extend': 6,\n",
    "        'hold': 7,\n",
    "    }\n",
    "    FINGERMODEL_IDS_INVERSE = {\n",
    "        0: 'rest',\n",
    "        1: 'cylinder',\n",
    "        2: 'ball',\n",
    "        3: 'flex',\n",
    "        4: 'double',\n",
    "        5: 'treble',\n",
    "        6: 'extend',\n",
    "        7: 'hold'\n",
    "    }\n",
    "    PROJECT_VERSION: str = '0.0.1'\n",
    "    DATA_PATH = './data'\n",
    "    MODEL_PATH = './static/models/ldaparm_TT.mat'\n",
    "    LOG_PATH = './static/log/log_TT/log20240308/arrow.log'\n",
    "\n",
    "\n",
    "settings = Settings()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python(NEO)",
   "language": "python",
   "name": "neo"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
